### ISSUE TITLE
Hand dictionary mutation bug

### ISSUE THREAD

**Issue by mart00n** [mart00n/introto6.00#3]
Bug in ps3a.py

Some function which examines the 'hand' of the player mutates the dictionary, even though all built in tests in module test_3a.py pass.

- all tests pass
- must be a function called by the game logic in play_hand() or play_game() in main()
- issue discovered by using 'repeat hand' command in play_game() logic - tested and repeatable

**Comment by y2kbugger** [comment]
I think I can handle this one—if you want me to take a look assign it to me.

Also, for clear communication get in the habit of using:
Steps: The specific series of steps or actions that the user took up until encountering the problem.
Expected result: What the user expected would occur after the step that immediately preceded the problem.
Actual result: What actually occurred after that final step/action.

**Comment by y2kbugger** [comment]
Heres a link to [play_game](https://github.com/mart00n/introto6.00/blob/e2f42dce30cb605f15724d34f606268082e48b99/ps3/ps3a.py#L271)

**Comment by y2kbugger** [comment]
what branch is this supposed to be in?

**Comment by mart00n** [comment]
Branch?

Only one left I believe, I merged the hw-help branch back in and pulled
your changes.

I think the game logic portion itself is actually causing the mutation, but
that seems impossible.

I also need to do some interface improvement and try some stuff on my own.
